color_mapping = {
    '白': 'White',
    '桃': 'Pink',
    '銀': 'Silver',
    '薄茶': 'Light Brown',
    '茶': 'Brown',
    '赤': 'Red',
    '青': 'Blue',
    '黒': 'Black',
    '緑': 'Green',
    '紫': 'Purple',
    '黄': 'Yellow',
    '灰': 'Gray',
    '象牙': 'Ivory',
    '金': 'Gold',
    '橙': 'Orange',
    '紺': 'Navy',
    '真珠': 'Pearl',
    '濃': 'Deep',
    '赤黒II': 'Red-Black II',
    '薄青': 'Light Blue',
    '桃白II': 'Peach-White II',
    '深銀Ｍ': 'Deep Silver M',
    '黒真珠': 'Black Pearl',
    '茶真珠': 'Brown Pearl',
    '銀Ｍ': 'Silver M',
    '赤Ｍ': 'Red M',
    '白橙II': 'White-Orange II',
    '灰桃II': 'Gray-Peach II',
    '緑真珠': 'Green Pearl',
    '桃銀Ｍ': 'Peach-Silver M',
    '濃緑Ｍ': 'Deep Green M',
    '赤銀Ｍ': 'Red-Silver M',
    '黒金II': 'Black-Gold II',
    '青Ｍ': 'Blue M',
    '青緑Ｍ': 'Blue-Green M',
    '青黒': 'Blue-Black',
    '青銀Ｍ': 'Blue-Silver M',
    '緑白II': 'Green-White II',
    '茶黒銀': 'Brown-Black-Silver',
    '桃真珠': 'Peach Pearl',
    '薄茶Ｍ': 'Light Brown M',
    '象牙': 'Ivory',
    '金': 'Gold',
    '赤真珠': 'Red Pearl',
    '黒黒': 'Black-Black',
    '紺真珠': 'Navy Pearl',
    '桃II': 'Peach II',
    '黒Ｍ': 'Black M',
    '金Ｍ': 'Gold M',
    '薄銀Ｍ': 'Light Silver M',
    '白Ｍ': 'White M',
    '緑Ｍ': 'Green M',
    '青II': 'Blue II',
    '濃紺': 'Deep Navy',
    '黒ＭＭ': 'Black M M',
    '灰Ｍ': 'Gray M',
    '薄紺Ｍ': 'Light Navy M',
    '赤灰': 'Red-Gray',
    '薄銀': 'Light Silver',
    '薄緑': 'Light Green',
    '緑濃': 'Green-Deep',
    '薄紺': 'Light Navy',
    '紺': 'Navy',
    '黄黒': 'Yellow-Black',
    '橙': 'Orange',
    '薄桃': 'Light Peach',
    '濃紺Ｍ': 'Deep Navy M',
    '赤黒': 'Red-Black',
    '紫真珠': 'Purple Pearl',
    '薄桃Ｍ': 'Light Peach M',
    '桃Ｍ': 'Peach M',
    '紫Ｍ': 'Purple M',
    '濃青': 'Deep Blue',
    '薄茶白': 'Light Brown-White',
    '黄象牙': 'Yellow-Ivory',
    '赤紫': 'Red-Purple',
    '薄薄茶': 'Very Light Brown',
    '橙Ｍ': 'Orange M',
    '深緑': 'Dark Green',
    '赤赤紫': 'Red-Red-Purple',
    '真珠III': 'Pearl III',
    '茶ＭII': 'Brown M II',
    '赤紫II': 'Red-Purple II',
    '桃薄': 'Peach-Light',
    '薄青Ｍ': 'Light Blue M',
    '赤桃Ｍ': 'Red-Peach M',
    '茶白': 'Brown White',
    '象牙Ｍ': 'Ivory M',
    '黒緑II': 'Black-Green II',
    '黒紫': 'Black-Purple',
    '薄茶薄': 'Light Brown-Light',
    '赤II': 'Red II',
    '薄紺白': 'Light Navy-White',
    '紫濃': 'Purple-Deep',
    '真珠黒': 'Pearl-Black',
    '緑白': 'Green-White',
    '灰黒': 'Gray-Black',
    '緑II': 'Green II',
    '赤白': 'Red-White',
    '緑II黒': 'Green II-Black',
    '薄黄': 'Light Yellow',
    '銅真珠': 'Copper Pearl',
    '濃紺銀': 'Deep Navy-Silver',
    '真珠II': 'Pearl II',
    '濃茶Ｍ': 'Deep Brown M',
    '青白II': 'Blue-White II',
    '黄II': 'Yellow II',
    'II': 'II',
    '白黄': 'White-Yellow',
    '真珠黄': 'Pearl Yellow',
    '橙銀Ｍ': 'Orange-Silver M',
    '薄青II': 'Light Blue II',
    '濃赤': 'Deep Red',
    '青II白': 'Blue II-White',
    '緑銀': 'Green-Silver',
    '薄茶II': 'Light Brown II',
    '茶黒': 'Brown-Black',
    '青灰': 'Blue-Gray',
    '黄Ｍ': 'Yellow M',
    '黒銀Ｍ': 'Black-Silver M',
    '濃紫': 'Deep Purple',
    '濃緑': 'Deep Green',
    '濃緑銀': 'Deep Green-Silver',
    '桃金銀': 'Peach-Gold-Silver',
    '茶赤紫': 'Brown-Red-Purple',
    '白桃Ｍ': 'White-Peach M',
    '桃Ｍ白': 'Peach M-White',
    '深紫': 'Dark Purple',
    '銀黒II': 'Silver-Black II',
    '茶灰': 'Brown-Gray',
    '青銀': 'Blue-Silver',
    '黄真珠': 'Yellow Pearl',
    '真珠赤': 'Pearl Red',
    '赤赤': 'Red-Red',
    '白青': 'White-Blue',
    '紺Ｍ': 'Navy M',
    '真珠緑': 'Pearl Green',
    '橙II': 'Orange II',
    '銀真珠': 'Silver Pearl',
    '薄緑Ｍ': 'Light Green M',
    '橙灰': 'Orange-Gray',
    '茶赤茶': 'Brown-Red-Brown',
    '赤ＭＭ': 'Red M M',
    '紺銀': 'Navy-Silver',
    '茶銀': 'Brown-Silver',
    '桃白': 'Peach-White',
    '赤桃': 'Red-Peach',
    '象牙黄': 'Ivory-Yellow',
    '象牙白': 'Ivory-White',
    '紺灰II': 'Navy-Gray II',
    '紺銀II': 'Navy-Silver II',
    '紫III': 'Purple III',
    '濃緑緑': 'Deep Green-Green',
    '白黒': "White-Black",
    '白真珠': "White Pearl",
    '茶Ｍ': "Brown M",
    '青真珠': "Blue Pearl",
    '真珠白': "Pearl White",
}







